version: '3.8'

services:
  siwake:
    build: .
    volumes:
      - .:/app
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]